### ISSUE TITLE
Inyeccion de dependencias

### ISSUE THREAD

**Issue by EdgardoSchiffer** [jhomikel/Sysaluarq#1]
Perdí mis ejemplos de Inyeccion de Dependencias, puede alguien acabar la inyeccion de OfertaDAO?

![screenshot_1](https://cloud.githubusercontent.com/assets/9885037/7240693/327a0178-e770-11e4-8ab6-50974add2328.png)

**Comment by jhomikel** [comment]
Hola Edgardo Chequealo y cualquier cosa me podes contactar en whatsapp al
7797-6113.

2015-04-20 15:16 GMT-06:00 Edgardo Bautista notifications@github.com:

> Perdí mis ejemplos de ID, puede alguien acabar la inyeccion de OfertaDAO?
> 
> [image: screenshot_1]
> https://cloud.githubusercontent.com/assets/9885037/7240693/327a0178-e770-11e4-8ab6-50974add2328.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jhomikel/Sysaluarq/issues/1.

## 

Ing. Jhony Mikel Escobar Galdámez
